version: '3.3'

services:
  db:
    container_name: database
    image: postgres:13-alpine
    env_file:
      - .env.db
    restart: always
    ports:
      - "5432:5432"
    networks:
      - my_net
    volumes:
      - ./postgresql:/var/lib/postgresql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

  django:
    container_name: djangoproject
    build:
      context: .
      dockerfile: Dockerfile
    command: python django_app.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    networks:
      - my_net
    restart: always
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    links:
      - db

  tgbot:
    container_name: bot
    build:
      context: .
    command: python main.py
    volumes:
    - .:/usr/src/app
    restart: always
    env_file:
      - .env
    networks:
      - my_net
    depends_on:
      - db
      - django

networks:
  my_net:
    driver: bridge
