# Generated by Django 4.1.7 on 2023-03-19 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.BigIntegerField(unique=True, verbose_name='ID пользователя телеграм')),
                ('name', models.CharField(max_length=50, verbose_name='Имя пользователя')),
                ('username', models.CharField(max_length=50, verbose_name='Username телеграм')),
                ('email', models.EmailField(max_length=60, verbose_name='Email')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
    ]
